<?php

/*
 * Copyright © 2016 Wyomind. All rights reserved.
 * See LICENSE.txt for license details.
 */

class Wyomind_Massstockupdate_Shell extends Mage_Shell_Abstract
{

    public $module = "massstockupdate";

    public function run()
    {


        try {

            $this->_validate();

            if ($this->getArg('run')) {
                if (is_string($this->getArg('run'))) {
                    $this->_run($this->getArg('run'));
                }
            } elseif ($this->getArg('sql')) {
                if (is_string($this->getArg('sql'))) {
                    $this->_sql($this->getArg('sql'));
                }
            } elseif ($this->getArg('list')) {
                $this->_list();
            } else {
                $this->_echo($this->usageHelp());
            }
        } catch (Exception $e) {
            $this->_echo("");
            Mage::logException($e);
            $this->_fault($e->getMessage());
        }
    }

    protected function _run($ids = null)
    {
        $collection = Mage::getModel($this->module . '/import')->getCollection();
        if ($ids != null) {
            $ids = explode(",", $ids);
            $collection->addFieldToFilter("profile_id", array("in", $ids));
        } else {
            exit('Please provide the profile ID to run');
        }

        if (count($collection) == 0) {
            $this->_fault("No profile found!");
        }

        foreach ($collection as $feed) {
            $this->_echo("\n\033[1mProcessing profile #" . $feed->getProfileId() . " : " . $feed->getProfileName() . "\033[0m\n\n");
            $feed->importProcess();
            $this->_echo("\n\n");
        }
    }

    protected function _sql($ids = null)
    {
        $collection = Mage::getModel($this->module . '/import')->getCollection();
        if ($ids != null) {
            $ids = explode(",", $ids);
            $collection->addFieldToFilter("profile_id", array("in", $ids));
        } else {
            exit('Please provide the profile ID to run');
        }

        if (count($collection) == 0) {
            $this->_fault("No profile found!");
        }

        foreach ($collection as $feed) {
            $this->_echo("\n\033[1mProcessing profile #" . $feed->getProfileId() . " : " . $feed->getProfileName() . "\033[0m\n\n");
            $feed->executeSql();
            $this->_echo("\n\n");
        }
    }

    protected function _list()
    {
        $collection = Mage::getModel($this->module . '/import')->getCollection();
        $this->_echo("");
        $row = sprintf(" %-6s | %-45s | %-22s", "#", "Profile", "Last Update");
        $this->_echo($row);
        $this->_echo("--------+-----------------------------------------------+---------------------");
        foreach ($collection as $feed) {
            $row = sprintf(
                    " %-6d | %-45s | %-22s", $feed->getProfileId(), $feed->getProfilePath() . $feed->getProfileName(), $feed->getImportedAt()
            );
            $this->_echo($row);
            $this->_echo("--------+-----------------------------------------------+---------------------");
        }
    }

    protected function _fault($str)
    {
        $this->_echo($str);
        exit;
    }

    protected function _echo($str)
    {
        fwrite(STDOUT, $str . PHP_EOL);
        return $this;
    }

    protected function _validate()
    {
        if (!Mage::isInstalled()) {
            exit('Please install magento before running this script.');
        }

        if (!Mage::helper('core')->isDevAllowed()) {
            exit('You are not allowed to run this script.');
        }

        if (!Mage::helper('core')->isModuleEnabled('Wyomind_Massstockupdate')) {
            exit('Please enable Woymind_' . ucFirst($this->module) . ' module before running this script.');
        }

        return true;
    }

    public function usageHelp()
    {
        return <<<USAGE
Usage:  php -f shell/wyomind_$this->module.php -- [options]

  -h                            Short alias for help
  --run  id1,id2,...,idN    Generate profile from the given list
  --sql  id1,id2,...,idN    Execute the sql file generated by the profile from the given list
  --list                        List all profiles
  help                          This help

USAGE;
    }

}