<div id="checkout-review" class="onepagecheckout_block">
    <div class="op_block_title"><h3 class="cor bold"><?php echo $this->__('Review Your Order') ?></h3></div>
    <br />
    <div id="checkout-review-load">
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <br />
    <div id="checkout-review-submit">    
        <?php echo $this->getChildHtml('agreements') ?>
        <div class="buttons-set" id="review-buttons-container">
	    <span><a style="margin:10px 0 0 10px;" class="f-l cor fs-14" href="<?php echo $this->getUrl('checkout/cart')?>" title="Editar carrinho">Editar carrinho</a></span>
        <button type="submit" title="<?php echo $this->__('Place Order Now') ?>" class="f-r button bt fs-16 d-b cor-sec bold tt-u radius td-n" onclick="checkout.save(); return false;"><?php echo $this->__('Place Order Now') ?></button>
        </div>
            <span class="txt fs-12 please-wait" id="review-please-wait" style="display:none;float:left;vertical-align: top;margin: 20px 0 0 10px;">
                <img src="<?php echo $this->getSkinUrl('images/onepagecheckout/loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
            </span>
    </div>
</div>
