#! /bin/bash
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Extensions.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/mysql4-data-install-1.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-data-install-4.0.0.php
rm ./app/code/local/Wyomind/Massproductimport/controllers/Adminhtml/MassproductimportController.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/mysql4-install-1.0.0.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-1.4.0-2.0.0.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-1.3.0-1.4.0.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-1.2.0-1.3.0.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-2.1.0-3.0.0.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-3.1.0-3.2.0.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Link.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-1.1.0-1.2.0.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-1.0.0-1.1.0.php
rm ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup/upgrade-2.0.0-2.1.0.php
rm ./app/code/local/Wyomind/Massstockupdate/controllers/Adminhtml/MassstockupdateController.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.10.0-3.10.1.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-4.0.0.5-5.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.10.1-3.11.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.9.2-3.10.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-1.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.11.0-4.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.3.1-3.4.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.9.1-3.9.2.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-5.0.0-6.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-6.0.0-7.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.9.0-3.9.1.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.2.0-3.3.1.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-1.0.1-2.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.1.0-3.2.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.8.0-3.9.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.7.0-3.8.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.4.0-3.4.1.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.0.0-3.1.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.6.0-3.7.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-2.0.0-3.0.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.5.0-3.6.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-3.4.1-3.5.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/upgrade-1.0.0-1.0.1.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/ConfigurableProductsAttribute.php
rm ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form/Field/Link.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/ConfigurableProductsCategory.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit/Tab/Advanced.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/ConfigurableProductsSystem.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit/Tab/Mapping.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit/Tab/Setting.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab/Advanced.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Renderer/Status.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Renderer/Action.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/ConfigurableProductsStock.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/ConfigurableProductsImage.php
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/ConfigurableProductsSystem.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab/Setting.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab/Mapping.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form/Field
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit/Tab/Cron.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Renderer/Action.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Renderer/Status.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab/Cron.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/DownloadableProduct.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit/Form.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/ConfigurableProduct.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit/Tabs.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config
rmdir  ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit/Tab
rmdir  ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Renderer
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form
rm ./app/design/adminhtml/default/default/template/massstockupdate/blackbox.phtml
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/AdvancedInventory.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Import/Collection.php
rm ./app/design/adminhtml/default/default/template/massstockupdate/mapping.phtml
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tabs.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Form.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab
rm ./app/code/local/Wyomind/Licensemanager/controllers/ActivationController.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Renderer
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Import/Collection.php
rm ./app/design/adminhtml/default/default/template/massstockupdate/empty.phtml
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/AdvancedInventory.php
rm ./app/design/adminhtml/default/default/template/massstockupdate/cron.phtml
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Grid.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit.php
rmdir  ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import/Edit
rmdir  ./app/code/local/Wyomind/Massproductimport/sql/massproductimport_setup
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Merchandising.php
rm ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/Notifications.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/CustomOption.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Grid.php
rm ./app/code/local/Wyomind/Massproductimport/Helper/Massproductimport.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Uploader.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Updater.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Attribute.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Uploader.php
rmdir  ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import
rm ./app/code/local/Wyomind/Notificationmanager/Model/Resource/Setup.php
rm ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml/Import.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Abstract.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Updater.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Category.php
rmdir  ./app/code/local/Wyomind/Massproductimport/controllers/Adminhtml
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Ignored.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import.php
rm ./app/code/local/Wyomind/Massstockupdate/Helper/Massstockupdate.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import
rm ./app/design/adminhtml/default/default/layout/massproductimport.xml
rmdir  ./app/design/adminhtml/default/default/template/massstockupdate
rmdir  ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Import
rmdir  ./app/code/local/Wyomind/Massstockupdate/controllers/Adminhtml
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/System.php
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Abstract.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Import.php
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Ignored.php
rm ./app/design/adminhtml/default/default/layout/massstockupdate.xml
rm ./app/code/local/Wyomind/Licensemanager/Helper/Licensemanager.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Image.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Price.php
rm ./app/code/local/Wyomind/Massproductimport/Model/Mysql4/Stock.php
rm ./app/design/adminhtml/default/default/layout/licensemanager.xml
rmdir  ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Import
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/System.php
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Import.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml
rm ./app/code/local/Wyomind/Notificationmanager/Model/Observer.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Resource
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Stock.php
rm ./js/lib/codemirror-5.36.0/addon/selection/selection-pointer.js
rm ./js/lib/codemirror-5.36.0/addon/runmode/runmode-standalone.js
rmdir  ./app/code/local/Wyomind/Massproductimport/Block/Adminhtml
rm ./js/lib/codemirror-5.36.0/addon/search/matchesonscrollbar.css
rm ./app/code/local/Wyomind/Notificationmanager/etc/adminhtml.xml
rm ./app/code/local/Wyomind/Massproductimport/Model/Observer.php
rm ./js/lib/codemirror-5.36.0/addon/search/matchesonscrollbar.js
rm ./js/lib/codemirror-5.36.0/addon/scroll/annotatescrollbar.js
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml
rm ./js/lib/codemirror-5.36.0/addon/scroll/simplescrollbars.css
rm ./js/lib/codemirror-5.36.0/addon/search/match-highlighter.js
rm ./app/code/local/Wyomind/Notificationmanager/Helper/Data.php
rm ./js/lib/codemirror-5.36.0/addon/selection/mark-selection.js
rm ./js/lib/codemirror-5.36.0/mode/htmlembedded/htmlembedded.js
rm ./skin/adminhtml/default/default/massstockupdate/resize.png
rm ./app/code/local/Wyomind/Massstockupdate/Model/Observer.php
rm ./skin/adminhtml/default/default/massstockupdate/import.css
rm ./js/lib/codemirror-5.36.0/addon/comment/continuecomment.js
rm ./app/code/local/Wyomind/Massproductimport/Model/Import.php
rmdir  ./app/code/local/Wyomind/Massproductimport/Model/Mysql4
rm ./skin/adminhtml/default/default/massstockupdate/loader.gif
rm ./skin/adminhtml/default/default/massstockupdate/updater.js
rm ./app/code/local/Wyomind/Notificationmanager/Model/Feed.php
rm ./app/code/local/Wyomind/Notificationmanager/etc/config.xml
rm ./app/code/local/Wyomind/Notificationmanager/etc/system.xml
rm ./js/lib/codemirror-5.36.0/addon/scroll/simplescrollbars.js
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml
rm ./app/code/local/Wyomind/Massproductimport/Helper/Data.php
rm ./app/code/local/Wyomind/Licensemanager/Model/Observer.php
rm ./skin/adminhtml/default/default/massstockupdate/import.js
rm ./js/lib/codemirror-5.36.0/mode/javascript/typescript.html
rm ./js/lib/codemirror-5.36.0/addon/lint/coffeescript-lint.js
rmdir  ./app/code/local/Wyomind/Massproductimport/controllers
rm ./skin/adminhtml/default/default/massstockupdate/icons.png
rmdir  ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4
rm ./js/lib/codemirror-5.36.0/addon/selection/active-line.js
rm ./app/code/local/Wyomind/Massproductimport/etc/system.xml
rm ./app/code/local/Wyomind/Massstockupdate/Model/Import.php
rm ./app/code/local/Wyomind/Massproductimport/etc/config.xml
rm ./js/lib/codemirror-5.36.0/mode/javascript/javascript.js
rm ./js/lib/codemirror-5.36.0/addon/hint/javascript-hint.js
rm ./js/lib/codemirror-5.36.0/addon/scroll/scrollpastend.js
rm ./js/lib/codemirror-5.36.0/addon/lint/javascript-lint.js
rm ./app/code/local/Wyomind/Massstockupdate/Helper/Data.php
rm ./js/lib/codemirror-5.36.0/addon/runmode/runmode.node.js
rmdir  ./app/code/local/Wyomind/Massstockupdate/controllers
rm ./app/code/local/Wyomind/Licensemanager/Helper/Data.php
rm ./js/lib/codemirror-5.36.0/mode/javascript/json-ld.html
rm ./js/lib/codemirror-5.36.0/mode/htmlembedded/index.html
rm ./js/lib/codemirror-5.36.0/addon/search/searchcursor.js
rm ./js/lib/codemirror-5.36.0/addon/display/autorefresh.js
rm ./app/code/local/Wyomind/Massstockupdate/etc/config.xml
rmdir  ./app/code/local/Wyomind/Licensemanager/controllers
rm ./app/code/local/Wyomind/Massstockupdate/etc/system.xml
rm ./js/lib/codemirror-5.36.0/addon/search/jump-to-line.js
rmdir  ./app/code/local/Wyomind/Notificationmanager/Helper
rm ./js/lib/codemirror-5.36.0/addon/display/fullscreen.css
rm ./js/lib/codemirror-5.36.0/addon/display/placeholder.js
rm ./js/lib/codemirror-5.36.0/addon/mode/multiplex_test.js
rm ./js/lib/codemirror-5.36.0/addon/edit/matchbrackets.js
rm ./js/lib/codemirror-5.36.0/addon/edit/trailingspace.js
rm ./app/code/local/Wyomind/Licensemanager/etc/config.xml
rm ./js/lib/codemirror-5.36.0/addon/fold/markdown-fold.js
rm ./js/lib/codemirror-5.36.0/addon/display/fullscreen.js
rm ./js/lib/codemirror-5.36.0/mode/htmlmixed/htmlmixed.js
rm ./js/lib/codemirror-5.36.0/addon/edit/closebrackets.js
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model
rm ./js/lib/codemirror-5.36.0/addon/edit/continuelist.js
rmdir  ./app/code/local/Wyomind/Massproductimport/Helper
rm ./js/lib/codemirror-5.36.0/addon/hint/anyword-hint.js
rm ./js/lib/codemirror-5.36.0/mode/javascript/index.html
rm ./js/lib/codemirror-5.36.0/addon/fold/comment-fold.js
rmdir  ./app/code/local/Wyomind/Massproductimport/Block
rmdir  ./app/code/local/Wyomind/Notificationmanager/etc
rmdir  ./app/code/local/Wyomind/Massproductimport/Model
rmdir  ./skin/adminhtml/default/default/massstockupdate
rm ./js/lib/codemirror-5.36.0/addon/runmode/colorize.js
rm ./js/lib/codemirror-5.36.0/addon/fold/indent-fold.js
rm ./js/lib/codemirror-5.36.0/mode/htmlmixed/index.html
rm ./js/lib/codemirror-5.36.0/addon/fold/foldgutter.css
rmdir  ./app/design/adminhtml/default/default/template
rmdir  ./app/code/local/Wyomind/Massstockupdate/Helper
rm ./js/lib/codemirror-5.36.0/addon/comment/comment.js
rm ./js/lib/codemirror-5.36.0/addon/hint/show-hint.css
rm ./js/lib/codemirror-5.36.0/addon/fold/foldgutter.js
rm ./js/lib/codemirror-5.36.0/addon/runmode/runmode.js
rm ./js/lib/codemirror-5.36.0/addon/fold/brace-fold.js
rmdir  ./app/code/local/Wyomind/Licensemanager/Helper
rm ./js/lib/codemirror-5.36.0/addon/dialog/dialog.css
rm ./js/lib/codemirror-5.36.0/addon/display/rulers.js
rm ./js/lib/codemirror-5.36.0/mode/javascript/test.js
rmdir  ./app/code/local/Wyomind/Massproductimport/sql
rm ./js/lib/codemirror-5.36.0/addon/edit/matchtags.js
rmdir  ./app/code/local/Wyomind/Massproductimport/etc
rmdir  ./app/code/local/Wyomind/Massstockupdate/Model
rm ./js/lib/codemirror-5.36.0/addon/mode/multiplex.js
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block
rm ./js/lib/codemirror-5.36.0/addon/lint/html-lint.js
rm ./js/lib/codemirror-5.36.0/addon/hint/html-hint.js
rm ./js/lib/codemirror-5.36.0/addon/hint/show-hint.js
rm ./js/lib/codemirror-5.36.0/addon/lint/json-lint.js
rm ./js/lib/codemirror-5.36.0/addon/lint/yaml-lint.js
rm ./js/lib/codemirror-5.36.0/addon/lint/css-lint.js
rm ./js/lib/codemirror-5.36.0/addon/wrap/hardwrap.js
rm ./js/lib/codemirror-5.36.0/addon/fold/xml-fold.js
rm ./js/lib/codemirror-5.36.0/addon/search/search.js
rm ./js/lib/codemirror-5.36.0/addon/dialog/dialog.js
rmdir  ./app/code/local/Wyomind/Licensemanager/Block
rm ./js/lib/codemirror-5.36.0/addon/hint/css-hint.js
rm ./app/etc/modules/Wyomind_Notificationmanager.xml
rmdir  ./app/code/local/Wyomind/Licensemanager/Model
rm ./js/lib/codemirror-5.36.0/addon/display/panel.js
rm ./js/lib/codemirror-5.36.0/addon/hint/sql-hint.js
rm ./js/lib/codemirror-5.36.0/addon/edit/closetag.js
rm ./js/lib/codemirror-5.36.0/addon/fold/foldcode.js
rm ./js/lib/codemirror-5.36.0/addon/hint/xml-hint.js
rm ./js/lib/codemirror-5.36.0/addon/mode/loadmode.js
rmdir  ./app/design/adminhtml/default/default/layout
rmdir  ./app/code/local/Wyomind/Massstockupdate/etc
rm ./js/lib/codemirror-5.36.0/bin/upload-release.js
rm ./js/lib/codemirror-5.36.0/addon/mode/overlay.js
rmdir  ./app/code/local/Wyomind/Notificationmanager
rm ./js/lib/codemirror-5.36.0/addon/merge/merge.css
rm ./js/lib/codemirror-5.36.0/mode/css/scss_test.js
rmdir  ./app/code/local/Wyomind/Massstockupdate/sql
rmdir  ./js/lib/codemirror-5.36.0/mode/htmlembedded
rm ./js/lib/codemirror-5.36.0/mode/clike/scala.html
rm ./js/lib/codemirror-5.36.0/mode/css/less_test.js
rm ./js/lib/codemirror-5.36.0/mode/clike/index.html
rm ./app/etc/modules/Wyomind_Massproductimport.xml
rmdir  ./app/code/local/Wyomind/Licensemanager/etc
rm ./js/lib/codemirror-5.36.0/mode/sass/index.html
rm ./js/lib/codemirror-5.36.0/bin/source-highlight
rm ./js/lib/codemirror-5.36.0/addon/mode/simple.js
rm ./js/lib/codemirror-5.36.0/mode/css/gss_test.js
rm ./js/lib/codemirror-5.36.0/addon/tern/worker.js
rm ./js/lib/codemirror-5.36.0/addon/merge/merge.js
rm ./js/lib/codemirror-5.36.0/mode/css/index.html
rm ./js/lib/codemirror-5.36.0/mode/clike/clike.js
rm ./js/lib/codemirror-5.36.0/addon/tern/tern.css
rm ./js/lib/codemirror-5.36.0/mode/php/index.html
rmdir  ./app/code/local/Wyomind/Massproductimport
rmdir  ./js/lib/codemirror-5.36.0/mode/javascript
rmdir  ./js/lib/codemirror-5.36.0/addon/selection
rm ./js/lib/codemirror-5.36.0/addon/lint/lint.css
rm ./js/lib/codemirror-5.36.0/mode/xml/index.html
rm ./js/lib/codemirror-5.36.0/mode/css/less.html
rm ./js/lib/codemirror-5.36.0/addon/lint/lint.js
rm ./js/lib/codemirror-5.36.0/mode/clike/test.js
rmdir  ./js/lib/codemirror-5.36.0/mode/htmlmixed
rm ./app/etc/modules/Wyomind_Massstockupdate.xml
rm ./js/lib/codemirror-5.36.0/mode/css/scss.html
rm ./js/lib/codemirror-5.36.0/lib/codemirror.css
rm ./js/lib/codemirror-5.36.0/addon/tern/tern.js
rmdir  ./js/lib/codemirror-5.36.0/addon/comment
rm ./app/etc/modules/Wyomind_Licensemanager.xml
rm ./js/lib/codemirror-5.36.0/keymap/sublime.js
rmdir  ./js/lib/codemirror-5.36.0/addon/runmode
rmdir  ./app/code/local/Wyomind/Massstockupdate
rmdir  ./js/lib/codemirror-5.36.0/addon/display
rm ./js/lib/codemirror-5.36.0/mode/sass/test.js
rm ./js/lib/codemirror-5.36.0/mode/css/gss.html
rm ./js/lib/codemirror-5.36.0/mode/sass/sass.js
rm ./js/lib/codemirror-5.36.0/lib/codemirror.js
rm ./js/lib/codemirror-5.36.0/theme/elegant.css
rmdir  ./app/code/local/Wyomind/Licensemanager
rm ./js/lib/codemirror-5.36.0/mode/php/test.js
rmdir  ./js/lib/codemirror-5.36.0/addon/dialog
rm ./js/lib/codemirror-5.36.0/mode/css/test.js
rm ./js/lib/codemirror-5.36.0/mode/xml/test.js
rmdir  ./js/lib/codemirror-5.36.0/addon/scroll
rmdir  ./js/lib/codemirror-5.36.0/addon/search
rmdir  ./js/lib/codemirror-5.36.0/addon/merge
rm ./js/lib/codemirror-5.36.0/mode/xml/xml.js
rm ./js/lib/codemirror-5.36.0/keymap/emacs.js
rm ./js/lib/codemirror-5.36.0/mode/index.html
rmdir  ./app/design/adminhtml/default/default
rm ./js/lib/codemirror-5.36.0/mode/css/css.js
rm ./js/lib/codemirror-5.36.0/mode/php/php.js
rmdir  ./js/lib/codemirror-5.36.0/mode/clike
rm ./js/lib/codemirror-5.36.0/bin/authors.sh
rmdir  ./js/lib/codemirror-5.36.0/addon/wrap
rmdir  ./js/lib/codemirror-5.36.0/addon/tern
rmdir  ./js/lib/codemirror-5.36.0/addon/mode
rmdir  ./js/lib/codemirror-5.36.0/addon/hint
rmdir  ./js/lib/codemirror-5.36.0/addon/lint
rmdir  ./js/lib/codemirror-5.36.0/addon/edit
rmdir  ./js/lib/codemirror-5.36.0/addon/fold
rmdir  ./js/lib/codemirror-5.36.0/mode/sass
rm ./js/lib/codemirror-5.36.0/keymap/vim.js
rm ./shell/WyomindMassStockUpdateShell.php
rmdir  ./js/lib/codemirror-5.36.0/mode/xml
rmdir  ./js/lib/codemirror-5.36.0/mode/php
rm ./js/lib/codemirror-5.36.0/mode/meta.js
rmdir  ./js/lib/codemirror-5.36.0/mode/css
rm ./js/lib/codemirror-5.36.0/bin/release
rmdir  ./js/lib/codemirror-5.36.0/keymap
rm ./shell/Wyomind_MassProductImport.php
rmdir  ./js/lib/codemirror-5.36.0/addon
rmdir  ./skin/adminhtml/default/default
rmdir  ./js/lib/codemirror-5.36.0/theme
rmdir  ./js/lib/codemirror-5.36.0/mode
rm ./shell/Wyomind_Massstockupdate.php
rm ./js/lib/codemirror-5.36.0/bin/lint
rm ./js/lib/codemirror-5.36.0/LICENSE
rmdir  ./js/lib/codemirror-5.36.0/bin
rmdir  ./js/lib/codemirror-5.36.0/lib
rmdir  ./app/design/adminhtml/default
rmdir  ./js/lib/codemirror-5.36.0
rmdir  ./skin/adminhtml/default
rmdir  ./app/code/local/Wyomind
rm ./js/lib/wyomind/uploader.js
rmdir  ./app/design/adminhtml
rm ./var/sample/inventory.csv
rm ./var/sample/update.xml
rmdir  ./app/etc/modules
rmdir  ./skin/adminhtml
rmdir  ./app/code/local
rmdir  ./js/lib/wyomind
rm ./var/tmp/empty.flag
rmdir  ./var/sample
rmdir  ./app/design
rmdir  ./app/code
rmdir  ./var/tmp
rmdir  ./app/etc
rmdir  ./js/lib
rmdir  ./shell
rmdir  ./skin
rmdir  ./app
rmdir  ./var
rmdir  ./js