<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php $_collectionSize = count($_products->getItems()) ?>

<div id="colunas9">&nbsp;</div>
<div id="colunas9" class="home-info">
	<h3 class="titleBox titleBox2"><span><strong>MAIS VENDIDOS</strong></span></h3>
</div>

<?php $i=1; foreach ($_products->getItems() as $_product): ?>
            <div id="colunas3" class=" prod <?php if($i%3==0 or $i==$_collectionSize){echo 'last';} ?>">
	            <div class="nova-h">  
	            <div class="tag-label">
	            <?php //label promoção por atributo ?>
	            <?php //if ($_product->getAttributeText('destaque') == "Sim"): ?>
					<!--<p style="position:absolute;">destaque</p>-->
				<?php //endif; ?>                
	            <?php // flag novo produto ?>
				<?php // Limit dates for newness
				$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
				$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
				// Date and time (now)
				$now = date("Y-m-d");
				if($newFromDate < $now && $newToDate >= $now): ?>
					<p class="novo">novidade</p>
				<?php endif; ?>
	            <?php // flag promoção ?>
				<?php
	    		// Get the Special Price
	    		$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
	    		// Get the Special Price FROM date
	    		$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
	    		// Get the Special Price TO date
	    		$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
	    		// Get Current date
	    		$today =  time(); 
	    		if ($specialprice):
	        		if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >=
	strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)): ?>
					<p class="oferta">promo&ccedil;&atilde;o</p>
				<?php  
	        		endif;
	    		endif; 
	    		?>
	            </div>
	    		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="img-prod" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(263); ?>" width="263" height="263" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
           		<div id="info-prod">
					<a class="fs-14 txt d-b" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><h2><?php echo $this->htmlEscape($_product->getName()) ?></h2></a>
					
					<!--R$ <?php //echo number_format($_product->getFinalPrice(), '2', '.', ','); ?>-->
					<?php echo $this->getPriceHtml($_product, true) ?>
					<div class="bt-nova">
						<a href="<?php echo $_product->getProductUrl() ?>" title="Comprar">Comprar</a>
					</div>
				</div>
	            </div><!-- end nova-h -->
            </div><!-- end colunas3 -->
  <?php $i++; endforeach; $kol = $_collectionSize; ?>

<?php endif; ?>