<?php
/**
 * AdaptiveShop - Mucci Estudio
 * ola@mucci.co
 */

/** Product list template
 * @see Mage_Catalog_Block_Product_List
 **/
?>

<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$this->_reviewsHelperBlock = $this->getLayout()->createBlock('review/helper');
?>

<div class="grid-produtos">

    <?php if(!$_productCollection->count()): ?>

        <div id="colunas9">
            <br />
            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        </div>

    <?php else: ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 3; ?>
    <?php $i=0; foreach ($_productCollection as $_product): $reqProductId = $_product->getId(); ?>
        <div id="colunas3" class=" prod <?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <div class="nova-h">
                <div class="tag-label">
                    <?php
                    $newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
                    $newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
                    $now = date("Y-m-d");

                    if($newFromDate < $now && $newToDate >= $now): ?>
                        <p class="novo">novidade</p>
                    <?php endif; ?>

                    <?php if($_product->isSaleable()): ?>
                    <?php else: ?>
                        <p class="novo">esgotado</p>
                    <?php endif; ?>
                </div>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <picture>
                        <img class="img-prod" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(260)->setQuality(70); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="263" heigth="263">
                    </picture>
                </a>
                <div id="info-prod">
                    <div class="mob">
                        <div class="list-rating"><?php echo $this->_reviewsHelperBlock->getSummaryHtml($_product, false, false); ?></div>
                    </div>
                    <a class="fs-18 txt d-b" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
                    </a>
                    <div class="mob">
                        <div class="price-box">
                        <?php echo $this->getPriceHtml($_product, true) ?>

                            <?php
                            $Preco = $_product->getFinalPrice();
                            if($Preco >= 100){
                                $Parcelamento = 2;
                                $Resultado = $Preco/ $Parcelamento;
                                echo '<p class="cor fs-15 bold">' . $Parcelamento .'x '.number_format($Resultado, 2, ',', '').' sem juros'. '</p>';
                            }
                            ?>
                        </div>
                        <div class="form-list-product" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                            <div class="list-qtd">
                                <span class="qtd-text">Qtd:</span>
                                <?php $loadProduct = Mage::getModel('catalog/product')->load( $_product->getId() );?>
                                <?php $minimal_quantity = $this->getMinimalQty($loadProduct); ?>
                                <?php if($_product->isSaleable()): ?>
                                 
                                    <span class="less">-</span>
                                    <input class="op-i qty" type="text" name="qty" id="qty" maxlength="5" value="<?php echo $this->getMinimalQty($loadProduct);?>" aria-label="Quantidade"/>
                                    <span class="more">+</span>
                                
                                <?php else: ?>
                                    <span class="less">-</span>
                                    <input class="op-i qty" type="text" name="qty" id="qty" maxlength="5" disabled="disabled" value="<?php echo $this->getMinimalQty($loadProduct);?>" aria-label="Quantidade"/>
                                    <span class="more">+</span>
                                <?php endif; ?>
                            </div>
                            <div class="bt-nova">
                                <button title="Comprar" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product, array('qty' => $minimal_quantity)) ?>'); return false">Adicionar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php $i++ ?>
        <?php if ($i == 8) break; ?>
    <?php endforeach ?>
    <?php endif; ?>
</div>

<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

<div id="colunas9">
    <?php
    $toolbar = $this->getToolbarBlock();
    $toolbar->setCollection($_productCollection);
    if($toolbar->getCollection()->getSize() > 0):
        echo $toolbar->getPagerHtml();
    endif;
    ?>
</div>

