<div id="colunas12">
    <?php
    //$guest_checkout2 = Mage::getStoreConfig('onepagecheckout/general/guest_checkout2');    
    //if ($guest_checkout2 === '1') :
    $logged		= $this->isCustomerLoggedIn(); 
     ?>
<?php if (!$logged): ?>
    <p class="onepagecheckout_loginarea fs-16 cor bold">
            <?php //echo $this->__('Already registered? Click here to login') ?>
            J&aacute; comprou com a gente?<br />
    </p>
    <a class="bt2 button fs-14 cor-sec bold f-l radius td-n" href="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>customer/account/login/" class="onepagecheckout_loginlink" >Fa&ccedil;a seu login</a>
    <br /><br />
    <div class="h-r f-l d-b"></div>
    <br />
    <h1 class="txt bold fs-16"><?php echo Mage::getStoreConfig('onepagecheckout/general/title') ?></h1>

    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>

    <?php
    $guest_checkout1 = Mage::getStoreConfig('onepagecheckout/general/guest_checkout1');
    if ($guest_checkout1 === '1') : ?>
    <p class="onepagecheckout_loginarea">
        <a href="javascript:void(0)" class="onepagecheckout_loginlink" onclick='open_login();'>
            <?php echo $this->__('Already registered? Click here to login') ?>
        </a>
    </p>
    <?php endif; ?>
    
	<?php 
	
		echo $this->getChildHtml('customer.login');
		echo $this->getChildHtml('customer.forgot');
	
    }    
    ?>

<?php else: ?>
	<br />
    <p class="onepagecheckout_loginarea fs-16 cor bold">
            Ol&aacute;, <?php echo $customerName = Mage::helper('customer')->getCustomerName(); ?>!<br />
    </p>
    <br />
    <div class="h-r f-l d-b"></div>
<?php endif; ?>

</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php
$seq_http	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
  
?>
<script type="text/javascript">
	var http_type	= '<?php if($seq_http){echo 'https';}else{echo 'http';}?>';
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/onepagecheckout.js') ?>"></script>

<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

<form action="" id="onepagecheckout_orderform">

<div id="colunas4">

    <div class="col1">
        <?php echo $this->getChildHtml('billing.address') ?>
        <?php echo $this->getChildHtml('shipping.address') ?>
    </div>

</div>
<div id="colunas4">

    <div class="col2">
        <?php echo $this->getChildHtml('shipping.method') ?>
        <br />
        <div class="h-r f-l d-b"></div>
        <br />
        <?php echo $this->getChildHtml('payment.method') ?>
        <br />
        <div class="h-r f-l d-b"></div>
        <br />
        <div id="checkout-coupon-discount-load">
            <?php echo $this->getChildHtml('coupon') ?>
        </div>
        <br />
        <div class="h-r f-l d-b"></div>
        <br />
        <?php if (Mage::getStoreConfig('onepagecheckout/general/comment')) : ?>
		<div class="op_block_title">
	    	<span class="cor fs-16 bold"><?php echo $this->helper('sales')->__('Comment') ?></span>
	    </div>        
        <div class="form_fields">
            <div class="full">
                <div class="data_area" id='comment-block'>
                    <textarea class="op-t txt fs-14" name="order-comment" id="order-comment"><?php echo trim(Mage::getSingleton('customer/session')->getOrderCustomerComment()) ?></textarea>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <input type="hidden" checked="checked" id="newsletter-signup" name="newsletter" value="1" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" />
        <!--
		<?php if (Mage::helper('onepagecheckout')->isSubscribeNewAllowed()) : ?>
            <p class="newsletter">
                <input type="hidden" checked="checked" id="newsletter-signup" name="newsletter" value="1" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" />
                <label for="newsletter-signup">
                    <?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>
                </label>
            </p>
        <?php endif; ?>
        -->
    </div>

</div>
<div id="colunas4">

    <div class="col3">
        <?php echo $this->getChildHtml('review') ?>
    </div>
</div>


</form>

<script type="text/javascript">
//<![CDATA[
    var checkout = new OPC('onepagecheckout_orderform', {
    	save    : '<?php echo $this->getUrl('onepagecheckout/index/saveOrder', array('_secure'=>$seq_http)) ?>',
    	update  : '<?php echo $this->getUrl('onepagecheckout/index/updateCheckout', array('_secure'=>$seq_http)) ?>',
        success : '<?php echo $this->getUrl('onepagecheckout/index/success', array('_secure'=>$seq_http)) ?>',
        failure : '<?php echo $this->getUrl('checkout/cart') ?>'
    }, "<?php echo $this->__('Please agree to all the terms and conditions.') ?>");

    document.observe("dom:loaded", function() {
        var win_triggers	= Array();
   		$$('.checkout-agreements .agree a').each(function(item){
   			var obj	= {
   				el: $$('.' + item.className),
   		   		event: 'click',
				window: $(item.className + '-window')
			};
   			win_triggers.push(obj);
        });
		opc_window	= new OPC.Window({triggers: win_triggers});
    });

//]]>
</script>





<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try{
    var pageTracker = _gat._getTracker("<?=Mage::getStoreConfig('onepagecheckout/general/analytics')?>");
    pageTracker._trackPageview();
    } catch(err) {}

</script>
