<?php
/**
 */
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get" class="f-r">
	<div class="form-search d-b f-l">
        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" placeholder="Digite aqui a sua busca" class="f-l d-b search txt fs-14" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
        <input type="submit" value="ok" title="<?php echo $this->__('Search') ?>" class="bt bt-s d-b f-l cor-sec bold tt-u fs-14" />
        <div id="search_autocomplete" class="search-autocomplete"></div>

    </div>
</form>