<?php echo $this->getChildHtml('ec_datalayer') ?>
<?php echo $this->getChildHtml('ec_visitor') ?>
<?php echo $this->getChildHtml('ec_dimensions') ?>
<?php echo $this->getChildHtml('ec_experiments') ?>
<?php echo $this->getChildHtml('ec_promotions') ?>
<script>

	var EC = [], Purchase = [], FacebookProducts = [];

	/* Dynamic remarketing */
	window.google_tag_params = window.google_tag_params || {};

	/* Default pagetype */
	window.google_tag_params.ecomm_pagetype = '<?php echo $this->helper('ec')->getPageType() ?>';

	/* Grouped products collection */
	window.G = [];

	/**
	 * Global revenue 
	 */
	window.revenue = 0;

	/**
	 * DoubleClick
	 */
	window.DoubleClick = 
	{
		DoubleClickRevenue:	 	0,
		DoubleClickTransaction: 0,
		DoubleClickQuantity: 	0
	}

	<?php if ($this->getOrderIds()) : ?>
	
		<?php 
		
			$collection = Mage::getResourceModel('sales/order_collection')->addFieldToFilter('entity_id', array
			(
				'in' => $this->getOrderIds())
			);
			
			foreach ($collection as $order) 
			{
				$products = $this->helper('ec')->getOrderProducts($order);
				
				?>

				var purchaseProducts = <?php echo Mage::helper('ec/json')->encode($products) ?>;
				
				var ecomm = 
				{
					i: [], /* ecomm_prodid[] array */
					v: [], /* ecomm_pvalue[] array */
					p: []  /* ecomm_pname[]  array */
				};

				jQuery.each(purchaseProducts, function(index, product)
				{
					ecomm.i.push(product.id);
					ecomm.v.push(product.price);
					ecomm.p.push(product.name);

					FacebookProducts.push(product.id);
				});
				
				<?php
				
				/* Sales coupon */
				$coupon = null;
				
				if ($order->getCouponCode())
				{
					$code = Mage::getModel('salesrule/coupon')->load($order->getCouponCode(), 'code');
					
					if ($code)
					{
						$rule = Mage::getModel('salesrule/rule')->load
						(
							$code->getRuleId()
						);
						
						$coupon = $rule->getName();
					}	
				}

				?>

				if (purchaseProducts.length)
				{
					var data = 
					{
						'ecommerce': 
						{
							'currencyCode': '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>',
							'purchase': 
							{
								'actionField': 
								{
									'id': 							'<?php echo 	$order->getIncrementId() ?>',
									'affiliation': 					'<?php echo 	$this->getAffiliation() ?>',
									'revenue': 						 <?php echo 	$this->getRevenue($order) ?>,
									'revenue_base':					 <?php echo 	$order->getBaseGrandTotal() ?>,
									'tax':							 <?php echo 	$order->getTaxAmount() ?>,
									'tax_base':						 <?php echo 	$order->getBaseTaxAmount() ?>,
									'shipping': 					 <?php echo 	$order->getShippingInclTax() ?>,
									'shipping_base':				 <?php echo 	$order->getBaseShippingAmount() ?>,
									'coupon':						'<?php echo 	$this->jsQuoteEscape($coupon) ?>',
									'coupon_discount_amount': 		'<?php echo 	$order->getDiscountAmount() ?>',
									'coupon_discount_amount_abs': 	'<?php echo abs($order->getDiscountAmount()) ?>',
									'coupon_code':					'<?php echo 	$order->getCouponCode() ?>'
								},
								'products': purchaseProducts
							}
						}
					};

					/**
					 * Push data to transport layer
					 */
					dataLayerTransport.push(data);

					/**
					 * Push purchase data
					 */
					Purchase.push(data);

					/**
					 * AdWords Dynamic Remarketing
					 */
					if (window.google_tag_params)
					{
						window.google_tag_params.ecomm_pagetype 	= 'purchase';
						
						window.google_tag_params.ecomm_prodid 		= ecomm.i;
						window.google_tag_params.ecomm_pvalue		= ecomm.v;
						window.google_tag_params.ecomm_pname		= ecomm.p;
						window.google_tag_params.ecomm_totalvalue 	= <?php echo (float) $this->getRevenue($order) ?>;

						<?php if ($this->helper('ec')->supportsDynx()): ?>

						window.google_tag_params.dynx_pagetype 		= 'conversion';
						window.google_tag_params.dynx_itemid 		= window.google_tag_params.ecomm_prodid;
						window.google_tag_params.dynx_totalvalue 	= window.google_tag_params.ecomm_totalvalue
						
						<?php endif ?>
					}

					<?php if ($this->getAdwords()->getGoogleConversionId()) : ?>

						window.google_conversion_id 		= '<?php echo $this->getAdwords()->getGoogleConversionId() ?>';
						window.google_conversion_value 		=  <?php echo $this->getRevenue($order) ?>;
						window.google_conversion_language 	= '<?php echo $this->getAdwords()->getGoogleConversionLanguage() ?>';
						window.google_conversion_format 	= '<?php echo $this->getAdwords()->getGoogleConversionFormat() ?>';
						window.google_conversion_label 		= '<?php echo $this->getAdwords()->getGoogleConversionLabel() ?>';
						window.google_conversion_color		= '<?php echo $this->getAdwords()->getGoogleConversionColor() ?>';
						window.google_conversion_currency 	= '<?php echo $this->getAdwords()->getGoogleConversionCurrency() ?>';
					
					<?php endif ?>
					
					/**
					 * Set revenue in global variable
					 */
					window.revenue = data.ecommerce.purchase.actionField.revenue;

					/**
					 * Set DoubleClick FloodLight Sales Revenue
					 */
					window.DoubleClick.DoubleClickRevenue 		= data.ecommerce.purchase.actionField.revenue;
					window.DoubleClick.DoubleClickTransaction 	= data.ecommerce.purchase.actionField.id;
					window.DoubleClick.DoubleClickQuantity 		= purchaseProducts.length;

					/**
					 * AdRoll Smart Pixel
					 */
					adroll_conversion_value 	= data.ecommerce.purchase.actionField.revenue;
					adroll_currency 			= "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>"
					adroll_custom_data 			= 
					{
						'ORDER_ID': data.ecommerce.purchase.actionField.id
					}

					<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
					
						adroll_custom_data['USER_ID'] = '<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId() ?>';
						
					<?php endif ?>
				

					/**
					 * Push DoubleClick to purchase
					 */
					Purchase.push(window.DoubleClick);
				}

				<?php 
			}
		?>
		
		
	<?php endif ?>

	if (Purchase.length)
	{
		<?php
		/**
		 * Push purchase data
		 */
		?>
		
		for (i = 0, l = Purchase.length; i < l; i++)
		{
			AEC.Cookie.purchase(Purchase[i]).push(dataLayer);
		}

		<?php
		/**
		 * Push custom purchase event
		 */
		?>

		AEC.Cookie.purchase(<?php echo Mage::helper('ec/json')->encode(array('event' => 'purchaseEvent')) ?>).push(dataLayer);

		/**
		 * Facebook Pixel Tracking
		 */
		<?php if ($this->helper('ec')->facebook()): ?>

			if ("undefined" !== typeof fbq)
			{
				fbq("track", "Purchase", 
				{
					content_ids:	FacebookProducts,
					content_type: 	'product',
					value: 			window.revenue,
					currency: 		'<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>'
				});
			}

		<?php endif ?>

		/**
		 * Clear persistant data from local storage
		 */
		AEC.Persist.clear();
	}
	
</script>
<script>AEC.Cookie.pushPrivate()</script>
<?php if ($this->getOrderIds()) : ?>
	<?php $collection = Mage::getResourceModel('sales/order_collection')->addFieldToFilter('entity_id', array('in' => $this->getOrderIds())); ?>
	<?php if ($this->getAdwords()->getGoogleConversionId()): ?>
		<script src="//www.googleadservices.com/pagead/conversion.js"></script>
	    <?php foreach ($collection as $order): ?>
			<noscript><img height=1 width=1 border=0 src="//www.googleadservices.com/pagead/conversion/<?php echo $this->getAdwords()->getGoogleConversionId() ?>/?value=<?php echo $this->getRevenue($order) ?>&label=<?php echo $this->getAdwords()->getGoogleConversionLabel() ?>&script=0"></noscript>
	    <?php endforeach ?>
    <?php endif ?>
    <?php foreach ($collection as $order): ?>
    	<?php echo $this->getLinkShare($order) ?>
    <?php endforeach ?>
<?php endif ?>
<?php echo $this->getChildHtml('ec_details') ?>
<?php echo $this->getChildHtml('ec_impression') ?>
<?php echo $this->getChildHtml('ec_search') ?>
<script>
	<?php if (Mage::getSingleton('core/session')->getCustomerLogin()): ?>
	
		dataLayer.push(
		{
			'event': 'customerLogin'
		});
	
		<?php Mage::getSingleton('core/session')->unsetData('customer_login') ?>
	
	<?php endif ?>
</script>
<script>
	<?php if (null !== $data = Mage::getSingleton('core/session')->getCartEmptyEvent()):?>
		dataLayer.push(<?php echo $data ?>);
		<?php Mage::getSingleton('core/session')->unsetData('cart_empty_event') ?>
	<?php endif ?>
	<?php if (null !== $data = Mage::getSingleton('core/session')->getCartUpdateEvent()):?>
		dataLayer.push(<?php echo $data ?>);
	<?php Mage::getSingleton('core/session')->unsetData('cart_update_event') ?>
<?php endif ?>
</script>
<?php echo $this->getChildHtml('ec_perfectaudience') ?>
<?php echo $this->getChildHtml('ec_adroll') ?>
<?php echo $this->getChildHtml('ec_cookie') ?>
<?php echo $this->helper('ec')->getHeadSnippet() ?>