<?php
/**
	ADAPTIVE SHOP - MUCCI ESTUDIO
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />

<title><?php echo $this->getTitle() ?></title>

<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<script type="text/javascript" src="<?php echo Mage::getBaseUrl() ?>js/owl-carousel/jquery-1.12.4.min.js?v=2"></script>

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>menu/component.css" />

<link rel="stylesheet" href="https://use.typekit.net/tuo5wln.css">

<script>
	!function(f,b,e,v,n,t,s)
	{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
	n.callMethod.apply(n,arguments):n.queue.push(arguments)};
	if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
	n.queue=[];t=b.createElement(e);t.async=!0;
	t.src=v;s=b.getElementsByTagName(e)[0];
	s.parentNode.insertBefore(t,s)}(window,document,'script',
	'https://connect.facebook.net/en_US/fbevents.js');
	
	 fbq('init', '1095330823857559'); 
	fbq('track', 'PageView');
</script>
<noscript>
	<img height="1" width="1" src="https://www.facebook.com/tr?id=1095330823857559&ev=PageView&noscript=1"/>
</noscript>

<?php
	$actionName = $this->getAction()->getFullActionName();
	if ($actionName == 'catalog_category_view')
	{
	    $category = Mage::registry('current_category');
	    $prodCol = $category->getProductCollection()->addAttributeToFilter('status', 1)->addAttributeToFilter('visibility', array('in' => array(Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG, Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH)));
	    $tool = $this->getLayout()->createBlock('page/html_pager')->setLimit($this->getLayout()->createBlock('catalog/product_list_toolbar')->getLimit())->setCollection($prodCol);
	    $linkPrev = false;
	    $linkNext = false;
	    if ($tool->getCollection()->getSelectCountSql()) {
	        if ($tool->getLastPageNum() > 1) {
	            if (!$tool->isFirstPage()) {
	                $linkPrev = true;
	                if ($tool->getCurrentPage() == 2) {
	                    $url = explode('?', $tool->getPreviousPageUrl());
	                    $prevUrl = @$url[0];
	                }
	                else {
	                    $prevUrl = $tool->getPreviousPageUrl();
	                }
	            }
	            if (!$tool->isLastPage()) {
	                $linkNext = true;
	                $nextUrl = $tool->getNextPageUrl();
	            }
	        }
	    }
	    if ($linkPrev) echo '<link rel="prev" href="' . $prevUrl . '" />';
	    if ($linkNext) echo '<link rel="next" href="' . $nextUrl . '" />';
	}
?>

<script src="<?php echo $this->getUrl('') ?>js/menu/modernizr.custom.js"></script>
<script src="<?php echo $this->getUrl('') ?>js/menu/jquery.dlmenu.js"></script>    