<?php
/**
 */
?>
	<div class="form-news d-b">
    	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
           	<input type="text" name="email" id="newsletter" value="" class="news-i txt fs-12 d-b input-text required-entry validate-email" autocomplete="off" placeholder="Digite seu email" maxlength="100">
            <input type="submit" value="assinar" class="bt fs-12 d-b bt-n cor-sec bold news-b">
        </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
	</div>

