<?php
/**
 * Shoping cart top
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<?php if ($this->getIsNeedToDisplaySideBar()):?>

    <?php $_cartQty = $this->getSummaryCount() ?>
    
	<div class="cart-container">

		<?php if ($_cartQty>0): ?>

				<?php if ($_cartQty==1): ?>

					<span class="bold cart cor-sec"><?php echo $this->__('<a href="%s"><svg width="26px" height="26px" viewBox="0 0 26 26" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
			<g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
				<g id="header" transform="translate(-1057.000000, -77.000000)" stroke="#C7B199">
					<g id="ico_carrinho/empty" transform="translate(1057.000000, 77.000000)">
						<g id="header_ico_Carrinho" transform="translate(1.000000, 1.000000)">
							<circle id="Oval" stroke-width="2" cx="9" cy="22" r="2"></circle>
							<circle id="Oval" stroke-width="2" cx="17" cy="22" r="2"></circle>
							<polyline id="Path-2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" points="0 0 3 2 6 18 21 18"></polyline>
							<polyline id="Path-3" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" points="4 4 24 5 22 14 6 14"></polyline>
						</g>
					</g>
				</g>
			</g>
		</svg> 1 item</a>', $this->getUrl('checkout/cart')) ?></span>
				<?php else: ?>

					<span class="bold cart cor-sec"><?php echo $this->__('<a href="%s"><svg width="26px" height="26px" viewBox="0 0 26 26" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
			<g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
				<g id="header" transform="translate(-1057.000000, -77.000000)" stroke="#C7B199">
					<g id="ico_carrinho/empty" transform="translate(1057.000000, 77.000000)">
						<g id="header_ico_Carrinho" transform="translate(1.000000, 1.000000)">
							<circle id="Oval" stroke-width="2" cx="9" cy="22" r="2"></circle>
							<circle id="Oval" stroke-width="2" cx="17" cy="22" r="2"></circle>
							<polyline id="Path-2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" points="0 0 3 2 6 18 21 18"></polyline>
							<polyline id="Path-3" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" points="4 4 24 5 22 14 6 14"></polyline>
						</g>
					</g>
				</g>
			</g>
		</svg> %s itens</a>', $this->getUrl('checkout/cart'), $_cartQty) ?></span>
				<?php endif ?>
				
		<?php else: ?>

			<span class="bold cart cor-sec">
			<a href="#" title="Carrinho Vazio">
				<svg width="26px" height="26px" viewBox="0 0 26 26" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
					<g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
						<g id="header" transform="translate(-1057.000000, -77.000000)" stroke="#C7B199">
							<g id="ico_carrinho/empty" transform="translate(1057.000000, 77.000000)">
								<g id="header_ico_Carrinho" transform="translate(1.000000, 1.000000)">
									<circle id="Oval" stroke-width="2" cx="9" cy="22" r="2"></circle>
									<circle id="Oval" stroke-width="2" cx="17" cy="22" r="2"></circle>
									<polyline id="Path-2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" points="0 0 3 2 6 18 21 18"></polyline>
									<polyline id="Path-3" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" points="4 4 24 5 22 14 6 14"></polyline>
								</g>
							</g>
						</g>
					</g>
				</svg>
				0 itens
			</a> 
			</span>
		<?php endif ?>
	</div>

	

    <div class="box-hover2">
    <div class="box-cart cor-sec fs-12">
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
        <ul id="cart-sidebar" class="mini-products-list">
        <?php foreach($_items as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        	<li>
        	<?php if ($this->canApplyMsrp()): ?>
        		<span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
            <?php else: ?>
            	<span class="f-l d-b cor-sec"><?php echo $this->__('Cart Subtotal:') ?> <span class="bold fs-14 cor-sec"><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></span></span>
            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
            	<br />
            	(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
            <?php endif; ?>
            <?php endif; ?>
            
            <?php //if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
            	<?php echo $this->getChildHtml('extra_actions') ?>
            	<button type="button" title="<?php echo $this->__('Checkout') ?>" class="f-r bt2 d-b cor-sec bold tt-u radius td-n" onclick="setLocation('https://www.bancadoramon.com.br/onestepcheckout/')"><?php echo $this->__('Checkout') ?></button>
   	        	<span><a class="f-r" href="<?php echo $this->getUrl('checkout/cart')?>" title="Editar carrinho">Editar carrinho</a></span>
   	        <?php //endif ?>
	       	</li>
        </ul>
        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
    <?php else: ?>
    <ul>
    	<li>
        <span class="cor-sec fs-14 bold d-b cart-empty">Nenhum item foi adicionado!<?php //echo $this->__('You have no items in your shopping cart.') ?></span>
    	</li>
    </ul>
    <?php endif ?>
    </div>
    </div>
<?php endif;?>
