<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<div id="onestepcheckout-review-comments-simple">
    <div>
        <div class="step-title"><h2>COMENTÁRIO DO PEDIDO</h2></div>
    	<textarea class="d-b op-t txt fs-14" name="comments" id="comments" rows="0" style="min-height: 100px;"><?php echo $this->getComments(); ?></textarea>
    </div>
</div>